server:
  port: 8088

spring:
  application:
    name: overseas
  datasource:
    url: jdbc:mysql://localhost:3306/db_yololiv_overseas?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      max-active: 20
  jackson:
    time-zone: GMT+8
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: root
    timeout: 20000
    jedis:
      pool:
        max-active: 200   # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 10000   # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: -1      # 连接池中的最大空闲连接
        min-idle: 0
#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.yololiv.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: false
    #逻辑删除配置
    logic-delete-value: 1
    logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    jdbc-type-for-null: null

email:
  protocol: smtp
  host: smtp.exmail.qq.com
  port: 465
  auth: true
  ssl_enable: true
  debug: true
  send_addr: dev@yololiv.com
  send_addr_pwd: Yunxi2015
  timeout: 10000
  connection_timeout: 10000
  write_timeout: 10000